### ISSUE TITLE
翻訳の概要と進捗状況

### ISSUE THREAD

**Issue by hoosan** [Japan-DfinityInfoHub/portal#1]
# 翻訳プロジェクトに参加するために

ドキュメントの翻訳は以下の手順で進めてください。

1. 翻訳ページ一覧を確認して、翻訳したい箇所をコメントしてください。
2. 翻訳する箇所はintroduction/pages/welcome.mdのように指定してください。また、 翻訳箇所は1ページずつでお願いします。
ただし、翻訳する人が少なく複数宣言しても問題ない場合は複数同時の担当も可とします。
3. 翻訳する前に、[スタイルガイド](https://github.com/Japan-DfinityInfoHub/docs/blob/main/styleguide.md)に目を通してください。
4. 校正や確認が終わったらプルリクエストを出してください。メンテナーが確認して、問題がなければマージされます。

もし、わからないことや質問等がある場合は [Discord](https://discord.gg/ewAxzfTURX) の #ドキュメント翻訳チャンネルで質問してください。
なお、宣言してから一定期間（目安：3ヶ月）プルリクエストがない場合には、担当を解除させていただきます。

# 原文のアップデートに応じた修正

原文のドキュメントがアップデートされたページには、:twisted_rightwards_arrows: の記号とプルリクへのリンクが記載されています（docsリポジトリからportalリポジトリへの移行時にアップデートされたドキュメントに関しては、プルリクへのリンクはありません）。
リンク先の diff を参考に翻訳を修正してプルリクを出してください。
修正を開始する前に、修正したい箇所をコメントしてください。

# メンテナーへ
コメントの確認からプルリクエストをマージする手順は以下に沿ってください。

## コメントを確認した場合
翻訳箇所のコメントを確認した場合、以下のフォーマットに沿って書き換えてください。作業中がわかるように🚀の絵文字をつけてください。この時点ではチェックマークは付けないでください。

こちらは一例です。

```
- [ ] introduction/pages/welcome.md (@hoosan):rocket:
```

## 翻訳のレビューが終わった場合
翻訳のチェックが終わってプルリクエストがマージされたら、以下のフォーマットに書き換えてください。
翻訳完了がわかるように🎉の絵文字をつけてください。
マージされた段階でチェックマークをつけるようにしてください。

```
- [x] introduction/pages/welcome.md (@hoosan):tada:
```

# 翻訳ページ一覧

- [x] what-is-the-ic/5_chain-key/index.md (@hokosugi) :tada:
- [x] what-is-the-ic/3_canisters/index.md (@hokosugi) :tada:
- [x] what-is-the-ic/4_consensus/index.md (@hokosugi) :tada:
- [x] what-is-the-ic/6_references/index.md (@hokosugi) :tada:
- [x] what-is-the-ic/2_nns/index.md (@hokosugi) :tada:
- [x] what-is-the-ic/1_ic/index.md (@hokosugi) :tada:
- [ ] docs/references/id-encoding-spec.md
- [ ] docs/references/security/rust-canister-development-security-best-practices.md
- [ ] docs/references/security/web-app-development-security-best-practices.md
- [ ] docs/references/security/index.md
- [ ] docs/references/security/general-security-best-practices.md
- [x] docs/references/candid-ref.md (@hoosan):tada:
- [ ] docs/references/ic-interface-spec.md
- [ ] docs/references/dfx-json-reference.md
- [ ] docs/references/index.md
- [ ] docs/references/ii-spec.md
- [ ] docs/references/ledger.md
- [ ] docs/references/_attachments/interface-spec-changelog.md
- [ ] docs/references/_attachments/ic0.md
- [x] docs/samples/overview.md (@pontagon333) :tada:
- [x] docs/samples/dex.md (@hokosugi) :tada:
- [x] docs/samples/host-a-website.md (@hokosugi) :tada:
- [x] docs/samples/dao.md (@hokosugi) :tada:
- [ ] docs/samples/host-unity-webgl.md
- [x] docs/samples/token-transfer.md (@hokosugi) :tada:
- [x] docs/samples/hello.md (@hokosugi) :tada:
- [ ] docs/samples/http-requests-exchange-rates.md
- [ ] docs/samples/t-ecdsa-sample.md
- [x] docs/samples/hackathon-projects.md (@hokosugi) :tada:
- [x] docs/samples/nft.md (@hokosugi) :tada:
- [x] docs/samples/deploying-your-first-bitcoin-dapp.md (@hoosan) :tada:
- [x] docs/samples/encrypted-notes.md (@hokosugi) :tada:
- [x] docs/concepts/nodes-subnets.md (@tokuryoo) :tada:
- [x] docs/concepts/governance.md (@numtet) :tada:
- [x] docs/concepts/data-centers.md (@tokuryoo) :tada:
- [ ] docs/concepts/trust-in-canisters.md
- [x] docs/concepts/index.md (@tokuryoo) :tada:
- [x] docs/concepts/tokens-cycles.md (@hoosan):tada:
- [x] docs/concepts/what-is-IC.md (@hoosan):tada:
- [ ] docs/concepts/canisters-code.md
- [ ] docs/tokenomics/sns/rewards.md
- [ ] docs/tokenomics/sns/predeployment-considerations.md
- [ ] docs/tokenomics/sns/governance-interaction.md
- [ ] docs/tokenomics/sns/sns-intro-tokens.md
- [ ] docs/tokenomics/sns/sale-interaction.md
- [ ] docs/tokenomics/sns/tokenomics.md
- [x] docs/tokenomics/identity-auth/hello-guide.md (@hoosan):tada:
- [x] docs/tokenomics/identity-auth/auth-how-to.md (@hoosan):tada:
- [x] docs/tokenomics/identity-auth/what-is-ic-identity.md (@hoosan):tada:
- [ ] docs/tokenomics/token-holders/custody-options-intro.md
- [ ] docs/tokenomics/token-holders/self-custody-quickstart.md
- [ ] docs/tokenomics/token-holders/nns-app-quickstart.md
- [ ] docs/tokenomics/token-holders/index.md
- [ ] docs/tokenomics/index.md
- [ ] docs/tokenomics/nns/nns-intro.md
- [ ] docs/tokenomics/nns/nns-staking-voting-rewards.md
- [ ] docs/tokenomics/nns/community-fund.md
- [ ] docs/developer-docs/deploy/scale.md
- [x] docs/developer-docs/deploy/custom-domain.md (@hokosugi) :tada:
- [ ] docs/developer-docs/deploy/advanced-deployment.md
- [x] docs/developer-docs/deploy/deploying-and-upgrading.md (@hokosugi) :tada:
- [x] docs/developer-docs/deploy/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/deploy/larger-wasm.md (@hokosugi) :tada:
- [x] docs/developer-docs/deploy/computation-and-storage-costs.md (@hokosugi) :tada:
- [x] docs/developer-docs/deploy/staging-environment.md (@hokosugi) :tada:
- [ ] docs/developer-docs/glossary.md
- [ ] docs/developer-docs/updates/release-notes/0.8.0-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.6.25-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.8.2-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.10.0-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.9.2-rn.md
- [ ] docs/developer-docs/updates/release-notes/release-notes.md
- [ ] docs/developer-docs/updates/release-notes/0.6.23-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.6.21-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.8.4-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.9.0-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.6.26-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.8.3-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.6.24-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.8.1-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.6.20-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.9.3-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.6.22-rn.md
- [ ] docs/developer-docs/updates/release-notes/sdk-release-notes.md
- [ ] docs/developer-docs/updates/release-notes/0.7.2-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.7.0-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.7.7-rn.md
- [ ] docs/developer-docs/updates/release-notes/0.7.1-rn.md
- [ ] docs/developer-docs/updates/index.md
- [x] docs/developer-docs/quickstart/cycles-faucet.md (@hokosugi) :tada:
- [x] docs/developer-docs/quickstart/cycles-faucet.md :twisted_rightwards_arrows:  (@hokosugi) :tada:
- [x] docs/developer-docs/quickstart/hello10mins.md (@hokosugi) :tada:
- [x] docs/developer-docs/quickstart/local-quickstart.md (@gelgoog999) :tada:
- [x] docs/developer-docs/quickstart/windows-wsl.md (@hokosugi) :tada:
- [x] docs/developer-docs/quickstart/hello20mins.md (@hokosugi) :tada:
- [x] docs/developer-docs/quickstart/network-quickstart.md (@gelgoog999) :tada:
- [x] docs/developer-docs/integrations/ledger/deploy-new-token.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/ledger/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/ledger/interact-with-ledger.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/ledger/ledger-local-setup.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/t-ecdsa/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/t-ecdsa/t-ecdsa-how-it-works.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/rosetta/staking-tutorial.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/rosetta/staking-support.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/rosetta/transfers.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/rosetta/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/rosetta/hotkeys.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/rosetta/neuron-lifecycle.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/internet-identity/integrate-identity.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/bitcoin/local-development.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/bitcoin/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/bitcoin/bitcoin-how-it-works.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/http_requests/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/integrations/http_requests/http_requests-how-it-works.md (@hokosugi) :tada:
- [ ] docs/developer-docs/integrations/sns/integrate-sns/ledger-integration.md
- [ ] docs/developer-docs/integrations/sns/integrate-sns/index-integration.md
- [ ] docs/developer-docs/integrations/sns/integrate-sns/frontend-integration.md
- [ ] docs/developer-docs/integrations/sns/managing-sns/manage-sns-intro.md
- [ ] docs/developer-docs/integrations/sns/managing-sns/proposal-guide.md
- [ ] docs/developer-docs/integrations/sns/managing-sns/nervous-system-parameters.md
- [ ] docs/developer-docs/integrations/sns/managing-sns/cycles-usage.md
- [ ] docs/developer-docs/integrations/sns/managing-sns/upgradeSNS.md
- [ ] docs/developer-docs/integrations/sns/sns-glossary.md
- [ ] docs/developer-docs/integrations/sns/get-sns/local-testing.md
- [ ] docs/developer-docs/integrations/sns/get-sns/preparation.md
- [ ] docs/developer-docs/integrations/sns/get-sns/get-sns-production.md
- [ ] docs/developer-docs/integrations/sns/get-sns/get-sns-intro.md
- [ ] docs/developer-docs/integrations/sns/index.md
- [ ] docs/developer-docs/integrations/sns/sns-intro.md
- [x] docs/developer-docs/integrations/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/frontend/webpack-config.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/frontend/my-contacts.md (@hokosugi) :tada:
- [ ] docs/developer-docs/build/frontend/index.md
- [x] docs/developer-docs/build/frontend/custom-frontend.md (@hokosugi) :tada:
- [ ] docs/developer-docs/build/troubleshooting.md
- [ ] docs/developer-docs/build/lang-service-ide.md
- [ ] docs/developer-docs/build/agents/ic-agent-dfinity.md
- [ ] docs/developer-docs/build/agents/index.md
- [ ] docs/developer-docs/build/agents/javascript/javascript-intro.md
- [ ] docs/developer-docs/build/agents/javascript/nodejs.md
- [x] docs/developer-docs/build/backend/multiple-actors.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/calculator.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/explore-templates.md (@pontagon333) :tada:
- [x] docs/developer-docs/build/backend/counter-tutorial.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/reproducible-builds.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/candid-ui.md (@hoosan):tada:
- [x] docs/developer-docs/build/backend/intercanister-calls.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/access-control.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/hello-location.md (@pontagon333) :tada:
- [x] docs/developer-docs/build/backend/multiple-factorial-actors.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/define-an-actor.md (@pontagon333) :tada:
- [x] docs/developer-docs/build/backend/simple-cycles.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/scalability-cancan.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/phonebook.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/backend/at-a-glance.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/project-setup/manage-canisters.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/project-setup/index.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/project-setup/design-dapps.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/project-setup/default-wallet.md (@hokosugi) :tada:
- [x] docs/developer-docs/build/project-setup/manage-projects.md (@hokosugi) :tada:
- [ ] docs/developer-docs/build/index.md
- [ ] docs/developer-docs/build/cdks/clang-supported-languages.md
- [ ] docs/developer-docs/build/cdks/index.md
- [ ] docs/developer-docs/build/cdks/azle-demergent-labs.md
- [x] docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-counter.md (@hoosan) :tada:
- [x] docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile.md (@hoosan) :tada:
- [x] docs/developer-docs/build/cdks/cdk-rs-dfinity/index.md (@hoosan) :tada:
- [x] docs/developer-docs/build/cdks/cdk-rs-dfinity/multiply-dependency.md (@hoosan) :tada:
- [x] docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-optimize.md (@hoosan) :tada:
- [x] docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-quickstart.md (@hoosan) :tada:
- [x] docs/developer-docs/build/candid/candid-concepts.md (@hoosan) :tada:
- [x] docs/developer-docs/build/candid/candid-howto.md (@hoosan) :tada:
- [x] docs/developer-docs/build/candid/candid-intro.md (@hoosan) :tada:
- [ ] docs/developer-docs/build/sample-apps.md
- [x] docs/developer-docs/best-practices/considerations-for-nft-devs.md (@hokosugi) :tada:
- [x] docs/developer-docs/best-practices/index.md (@hokosugi) :tada:

## SDK

以下のドキュメントの翻訳は、[Japan-DfinityInfoHub/sdk](https://github.com/Japan-DfinityInfoHub/sdk) を fork して実施してください🙏
- [ ] docs/cli-reference/dfx-info.md
- [x] docs/cli-reference/dfx-help.md (@hokosugi) :tada:
- [ ] docs/cli-reference/dfx-new.md
- [ ] docs/cli-reference/dfx-ping.md
- [x] docs/cli-reference/dfx-cache.md (@hokosugi) :tada:
- [ ] docs/cli-reference/dfx-start.md
- [x] docs/cli-reference/dfx-generate.md (@hokosugi) :tada:
- [ ] docs/cli-reference/dfx-schema.md
- [ ] docs/cli-reference/dfx-wallet.md
- [x] docs/cli-reference/dfx-build.md (@hokosugi) :tada:
- [x] docs/cli-reference/dfx-canister.md (@hokosugi) :tada:
- [ ] docs/cli-reference/dfx-canister.md 🔀 
- [ ] docs/cli-reference/dfx-sns.md
- [ ] docs/cli-reference/dfx-replica.md
- [ ] docs/cli-reference/dfx-upgrade.md
- [ ] docs/cli-reference/dfx-stop.md
- [ ] docs/cli-reference/index.md
- [x] docs/cli-reference/dfx-deploy.md (@hokosugi) :tada:
- [ ] docs/cli-reference/dfx-bootstrap.md
- [ ] docs/cli-reference/dfx-parent.md
- [ ] docs/cli-reference/dfx-ledger.md
- [x] docs/cli-reference/dfx-identity.md (@hokosugi) :tada:
- [x] docs/cli-reference/dfx-envars.md (@hokosugi) :tada:
- [x] docs/cli-reference/dfx-config.md (@hokosugi) :tada:

## Motoko

以下のドキュメントの翻訳は、[Japan-DfinityInfoHub/motoko](https://github.com/Japan-DfinityInfoHub/motoko) を fork して実施してください🙏

- [ ] doc/overview-slides.md
- [ ] doc/README.md
- [x] doc/md/compiler-ref.md (@hoosan):tada:
- [ ] doc/md/about-this-guide.md
- [ ] doc/md/message-inspection.md
- [ ] doc/md/overview.md
- [x] doc/md/cycles.md (@hoosan):tada:
- [ ] doc/md/stablememory.md
- [ ] doc/md/base-intro.md
- [x] doc/md/actors-async.md (@hoosan):tada:
- [ ] doc/md/heartbeats.md
- [ ] doc/md/structural-equality.md
- [x] doc/md/pattern-matching.md (@hoosan):tada:
- [x] doc/md/motoko-introduction.md (@hoosan):tada:
- [x] doc/md/motoko.md (@hoosan):tada:
- [x] doc/md/errors.md (@hoosan):tada:
- [x] doc/md/upgrades.md (@hoosan):tada:
- [x] doc/md/caller-id.md (@hoosan):tada:
- [ ] doc/md/local-objects-classes.md
- [ ] doc/md/style.md
- [ ] doc/md/advanced-discussion.md
- [x] doc/md/control-flow.md (@hoosan):tada:
- [x] doc/md/motoko-grammar.md (@hoosan):tada:
- [ ] doc/md/compatibility.md
- [ ] doc/md/extrastuff.md
- [x] doc/md/sharing.md (@hoosan):tada:
- [ ] doc/md/language-manual.md
- [x] doc/md/modules-and-imports.md (@hoosan):tada:
- [x] doc/md/actor-classes.md (@hoosan):tada:
- [x] doc/md/mutable-state.md (@hoosan):tada:
- [ ] doc/md/base/Buffer.md
- [ ] doc/md/base/Text.md
- [ ] doc/md/base/Stack.md
- [ ] doc/md/base/Debug.md
- [ ] doc/md/base/Prelude.md
- [ ] doc/md/base/Int32.md
- [ ] doc/md/base/Int16.md
- [ ] doc/md/base/AssocList.md
- [ ] doc/md/base/Result.md
- [ ] doc/md/base/Hash.md
- [ ] doc/md/base/ExperimentalCycles.md
- [ ] doc/md/base/Int.md
- [ ] doc/md/base/Blob.md
- [ ] doc/md/base/Int8.md
- [ ] doc/md/base/Trie.md
- [ ] doc/md/base/HashMap.md
- [ ] doc/md/base/ExperimentalStableMemory.md
- [ ] doc/md/base/CertifiedData.md
- [ ] doc/md/base/IterType.md
- [ ] doc/md/base/Func.md
- [ ] doc/md/base/Nat32.md
- [ ] doc/md/base/Nat16.md
- [ ] doc/md/base/Array.md
- [ ] doc/md/base/Deque.md
- [ ] doc/md/base/Error.md
- [ ] doc/md/base/List.md
- [ ] doc/md/base/Heap.md
- [ ] doc/md/base/RBTree.md
- [ ] doc/md/base/Nat64.md
- [ ] doc/md/base/Option.md
- [ ] doc/md/base/index.md
- [ ] doc/md/base/Principal.md
- [ ] doc/md/base/Iter.md
- [ ] doc/md/base/Time.md
- [ ] doc/md/base/None.md
- [ ] doc/md/base/TrieSet.md
- [ ] doc/md/base/Nat.md
- [ ] doc/md/base/Random.md
- [ ] doc/md/base/ExperimentalInternetComputer.md
- [ ] doc/md/base/Nat8.md
- [ ] doc/md/base/TrieMap.md
- [ ] doc/md/base/Bool.md
- [ ] doc/md/base/Int64.md
- [ ] doc/md/base/Float.md
- [ ] doc/md/base/Order.md
- [ ] doc/md/base/Char.md
- [x] doc/md/basic-concepts.md (@hoosan):tada:
- [ ] doc/docusaurus/README.md
- [ ] doc/docusaurus/src/pages/markdown-page.md

## Quill

以下のドキュメントの翻訳は、[Japan-DfinityInfoHub/quill](https://github.com/Japan-DfinityInfoHub/quill) を fork して実施してください🙏

- [ ] docs/cli-reference/quill-transfer.md
- [ ] docs/cli-reference/quill-update-node-provider.md
- [ ] docs/cli-reference/quill-neuron-stake.md
- [ ] docs/cli-reference/quill-parent.md
- [ ] docs/cli-reference/quill-get-neuron-info.md
- [ ] docs/cli-reference/quill-account-balance.md
- [ ] docs/cli-reference/quill-replace-node-provider-id.md
- [ ] docs/cli-reference/quill-list-neurons.md
- [ ] docs/cli-reference/quill-get-proposal-info.md
- [ ] docs/cli-reference/quill-scanner-qr-code.md
- [ ] docs/cli-reference/quill-neuron-manage.md
- [ ] docs/cli-reference/index.md
- [ ] docs/cli-reference/quill-send.md
- [ ] docs/cli-reference/quill-generate.md
- [ ] docs/cli-reference/quill-claim-neurons.md
- [ ] docs/cli-reference/quill-list-proposals.md
- [ ] docs/cli-reference/quill-qr-code.md
- [ ] docs/cli-reference/quill-public-ids.md

## Roadmap

以下は本家の更新が頻繁なので優先度低いです

- [ ] roadmap/6_infrastructure/in-progress/3_bazel.md
- [ ] roadmap/6_infrastructure/in-progress/2_replica-storage-upgrade.md
- [ ] roadmap/6_infrastructure/in-progress/1_new-hw-spec.md
- [ ] roadmap/6_infrastructure/index.md
- [ ] roadmap/2_boundary_nodes/in-progress/1_seo_and_streaming.md
- [ ] roadmap/2_boundary_nodes/in-progress/3_custom_domains.md
- [ ] roadmap/2_boundary_nodes/in-progress/2_asset_canister_caching.md
- [ ] roadmap/2_boundary_nodes/deployed/icos-nodes.md
- [ ] roadmap/2_boundary_nodes/index.md
- [ ] roadmap/2_boundary_nodes/pending/canister_blacklisting.md
- [ ] roadmap/2_boundary_nodes/pending/sev_snp_nodes.md
- [ ] roadmap/2_boundary_nodes/pending/custom_subdomains.md
- [ ] roadmap/1_core-protocol/in-progress/4_high-replication-subnets.md
- [ ] roadmap/1_core-protocol/in-progress/1_btc-integration.md
- [ ] roadmap/1_core-protocol/in-progress/5_deterministic-time-slicing.md
- [ ] roadmap/1_core-protocol/in-progress/2_tecdsa.md
- [ ] roadmap/1_core-protocol/in-progress/3_http-outcalls.md
- [ ] roadmap/1_core-protocol/deployed/network_performance.md
- [ ] roadmap/1_core-protocol/deployed/nodes_can_be_reassigned.md
- [ ] roadmap/1_core-protocol/index.md
- [ ] roadmap/1_core-protocol/pending/eth-integration.md
- [ ] roadmap/4_governance_nns/in-progress/1_sns.md
- [ ] roadmap/4_governance_nns/in-progress/3_enhance_replica_version_management.md
- [ ] roadmap/4_governance_nns/in-progress/2_community_fund.md
- [ ] roadmap/4_governance_nns/deployed/open_governance.md
- [ ] roadmap/4_governance_nns/index.md
- [ ] roadmap/5_developer_experience/in-progress/3_system-wide-dfx.md
- [ ] roadmap/5_developer_experience/in-progress/4_dfx_quickstart.md
- [ ] roadmap/5_developer_experience/in-progress/1_btc_integration_in_dfx.md
- [ ] roadmap/5_developer_experience/in-progress/2_sns_quill.md
- [ ] roadmap/5_developer_experience/index.md
- [ ] roadmap/5_developer_experience/pending/cycles_wallet_deprecation.md
- [ ] roadmap/5_developer_experience/pending/mainnet_logging.md
- [ ] roadmap/3_system_utils_and_dapps/in-progress/adding_np_role_to_nns_fe_dapp.md
- [ ] roadmap/3_system_utils_and_dapps/deployed/nns_fe_dapp_rewrite.md
- [ ] roadmap/3_system_utils_and_dapps/index.md
- [ ] roadmap/3_system_utils_and_dapps/pending/people_parties.md

## How-it-works

以下は本家の更新が頻繁なので優先度低いです

- [ ] how-it-works/1_about/08_network-nervous-system-nns.subpage.md
- [ ] how-it-works/1_about/07_canister-lifecycle.card.md
- [ ] how-it-works/1_about/07_canister-lifecycle.subpage.md
- [ ] how-it-works/1_about/02_chain-key-technology.card.md
- [ ] how-it-works/1_about/04_peer-to-peer-p2p.card.md
- [ ] how-it-works/1_about/11_upgrades.subpage.md
- [ ] how-it-works/1_about/09_state-synchronization.card.md
- [ ] how-it-works/1_about/08_network-nervous-system-nns.card.md
- [ ] how-it-works/1_about/03_noninteractive-distributed-key-generation-nidkg.subpage.md
- [ ] how-it-works/1_about/06_message-routing.card.md
- [ ] how-it-works/1_about/10_resumption.card.md
- [ ] how-it-works/1_about/05_consensus.card.md
- [ ] how-it-works/1_about/01_overview-of-the-internet-computer.subpage.md
- [ ] how-it-works/1_about/01_overview-of-the-internet-computer.card.md
- [ ] how-it-works/1_about/03_noninteractive-distributed-key-generation-nidkg.card.md
- [ ] how-it-works/1_about/09_state-synchronization.subpage.md
- [ ] how-it-works/1_about/index.md
- [ ] how-it-works/1_about/12_ingress-message-lifecycle.subpage.md
- [ ] how-it-works/1_about/05_consensus.subpage.md
- [ ] how-it-works/1_about/04_peer-to-peer-p2p.subpage.md
- [ ] how-it-works/1_about/10_resumption.subpage.md
- [ ] how-it-works/1_about/06_message-routing.subpage.md
- [ ] how-it-works/1_about/11_upgrades.card.md
- [ ] how-it-works/1_about/12_ingress-message-lifecycle.card.md
- [ ] how-it-works/1_about/02_chain-key-technology.subpage.md
- [ ] how-it-works/test.subpage.md
- [ ] how-it-works/test.card.md
- [ ] how-it-works/3_features/threshold-ecdsa-signing.subpage.md
- [ ] how-it-works/3_features/threshold-ecdsa-signing.card.md
- [ ] how-it-works/3_features/direct-integration-with-bitcoin.card.md
- [ ] how-it-works/3_features/index.md
- [ ] how-it-works/3_features/web-authentication-identity.subpage.md
- [ ] how-it-works/3_features/direct-integration-with-bitcoin.subpage.md
- [ ] how-it-works/3_features/sns.card.md
- [ ] how-it-works/3_features/web-authentication-identity.card.md
- [ ] how-it-works/2_components/motoko.subpage.md
- [ ] how-it-works/2_components/motoko.card.md
- [ ] how-it-works/2_components/index.md
- [ ] how-it-works/2_components/response-certification.card.md
- [ ] how-it-works/2_components/response-certification.subpage.md

**Comment by henrysmit420** [comment]
Mine for free here ..
https://www.btcs.love/invite/4nc58

**Comment by hokosugi** [comment]
翻訳します。

* what-is-the-ic/5_chain-key/index.md
 * what-is-the-ic/3_canisters/index.md
 * what-is-the-ic/4_consensus/index.md
 * what-is-the-ic/6_references/index.md
 * what-is-the-ic/2_nns/index.md
 * what-is-the-ic/1_ic/index.md

**Comment by hokosugi** [comment]
*adocファイルからmdファイル移行*

ファイル転換が出来ることを確認しましたので

docs/developer-docs/quickstartからやっていきます。

**Comment by hokosugi** [comment]
portal/docs/developer-docs/integrations/bitcoin/
の3ファイルを翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/integrations/t-ecdsaの2ファイルを翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/integrations/http_requestsの２ファイルを翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/integrations/internet-identity の１ファイルを翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/integrations/ledgerの4ファイルを翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/integrations/rosettaの６ファイルを翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/integrations/index.mdを翻訳します。
SNSも一部公開されていて興味ありますが、未公開もあり更新される可能性も高そうなので、これでintegrationsは離れて別のフォルダに移ります。

**Comment by hokosugi** [comment]
docs/developer-docs/build/project-setupの５ファイルを翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/build/backendの１６ファイルを翻訳します。
いくつかは翻訳済みなので確認と元ドキュメントを参考にしつつやっていきます。

**Comment by tokuryoo** [comment]
docs/references/ii-spec.md を翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/best-practicesの２ファイル（considerations-for-nft-devs.md, index.md）を翻訳します。

**Comment by hokosugi** [comment]
docs/developer-docs/deployの８ファイルを翻訳します。

**Comment by tokuryoo** [comment]
すみません、docs/references/ii-spec.md の翻訳、取り下げます。
